# Use an official OpenJDK runtime as a parent image
FROM amazoncorretto:17

# Set the working directory in the container
WORKDIR /app

# Copy the Java source code to the container
COPY src/main/java/com/example/HelloWorld.java /app/.

# Compile the Java program
RUN javac /app/HelloWorld.java

# Command to run the Java application
CMD ["java", "HelloWorld"]
